# Default values for minecraft-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "docker.io/jozseftorocsik/test"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "minecraft-server"

imagePullSecrets: []
  #- name: "docker-pull-secret"
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

service:
  type: ClusterIP
  port: 25565
