apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minecraft-server.fullname" . }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi