apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft-server.fullname" . }}
  namespace: servers
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minecraft-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minecraft-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          volumeMounts:
          - mountPath: "/world"
            name: world-save
      volumes:
        - name: world-save
          persistentVolumeClaim:
            claimName: {{ include "minecraft-server.fullname" . }}-pvc