apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-server.fullname" . }}
  namespace: servers
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft
  selector:
    {{- include "minecraft-server.selectorLabels" . | nindent 4 }}
