apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include "deployer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deployer.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "deployer.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "deployer.fullname" . }}
  apiGroup: ""