apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deployer.fullname" . }}
  labels:
    {{- include "deployer.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "create", "delete", "list", "patch", "update", "watch"]