name: Docker Image CI

on:
  push:
    branches: [ "development" ]

jobs:
  

  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: 'Set build id'
        id: build_id
        # add a step output `steps.build_id.outputs.id` as the unique id
        run: echo "::set-output name=id::$(date +%s)"


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "jozseftorocsik/szakdolgozat-deployer"
      
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
          persist-credentials: false

      
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "buildVersion:*"
          replace: "buildVersion: ${{steps.build_id.outputs.id}}"
          include: "helm/deployer/values.yaml"
          regex: true
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Merge development -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ secrets.GIT_TOKEN }}
          
