name: Docker Image CI

on:
  push:
    branches: [ "development" ]

jobs:
  

  build:

    runs-on: ubuntu-latest
    
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "jozseftorocsik/szakdolgozat-deployer"
      
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
          persist-credentials: false
      
      - name: 'Set build id'
        id: build_id
        # add a step output `steps.build_id.outputs.id` as the unique id
        run: echo "::set-output name=id::$(date +%s)"
        
      - name: 'Save build id'
        run: |
        env:
          BUILD_ID: ${{ steps.build_id.outputs.id }}

      
      - name: Update build number
        run: |
          echo $BUILD_ID
          sed -i "/buildVersion:*/c\buildVersion: ${BUILD_ID}" helm/deployer/values.yaml
          cat helm/deployer/values.yaml
          
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: development
          
      - name: Merge development -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ secrets.GIT_TOKEN }}
          
